name: Create releases for updated packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**/package.json'

jobs:
  publish:
    name: Publish ${{ matrix.package.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      # an awkward consequence is that dependencies might not get published
      # but nothing to do about that in a workflow
      fail-fast: false
      matrix:
        package:
          - name: com.timiz0r.ezutils.common
            path: ./src/EZUtils.Common
          - name: com.timiz0r.ezutils.mmdavatartools
            path: ./src/EZUtils.MMDAvatarTools
          - name: com.timiz0r.ezutils.repackprefab
            path: ./src/EZUtils.RepackPrefab
          - name: com.timiz0r.ezutils.windowcloser
            path: ./src/EZUtils.WindowCloser
          - name: com.timiz0r.ezutils.editorenhancements
            path: ./src/EZUtils.EditorEnhancements
          - name: com.timiz0r.ezutils.localization
            path: ./src/EZUtils.Localization
          - name: com.timiz0r.ezutils.localization.extraction
            path: ./src/EZUtils.Localization.Extraction
          - name: com.timiz0r.ezutils.vpmunitypackage
            path: ./src/EZUtils.VPMUnityPackage
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
    #   - name: Publish UPM package
    #     uses: ./.github/actions/publish-upm-package
    #     with:
    #       package-path: ${{ matrix.package.path }}
      - uses: ./.github/actions/publish-vpm-package
        with:
          package-path: ${{ matrix.package.path }}
          index-path: vpm/index.json
  update-index:
    name: Update package index
    needs: publish
    #we allow individual package publishes to fail, but we still want to finish successful ones
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - name: Get manifests
        uses: actions/download-artifact@v4
        with:
          path: vpm
      - uses: ./.github/actions/update-index-json
  publish-index:
    uses: ./.github/workflows/publish-vpm-changes.yaml
    needs: update-index



